<?php

/**
* hook_form_alter
*/
function site_information_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {

    if(!empty(variable_get('siteapikey'))) {
      $form['actions']['submit']['#value'] = t('Update configuration');
    }

    $form['site_information']['siteapikey'] = array(
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => !empty(variable_get('siteapikey')) ? variable_get('siteapikey') : 'No API Key yet',
    );

    $form['#submit'][] = 'site_information_form_submit';
  }
}

/**
* Submit function for site_information_form_alter
*/
function site_information_form_submit($form, &$form_state){

  if(!empty($form_state['values']['siteapikey'])){
        variable_set('siteapikey', $form_state['values']['siteapikey']);
  
    drupal_set_message('Site API Key has been saved');
    }

}